FROM golang:1.23.5-bullseye

ENV GOPROXY=https://proxy.golang.org,direct
ENV GO111MODULE="on"
ENV GOOS="linux"
ENV CGO_ENABLED=0

RUN apt install ca-certificates git 

RUN go install github.com/air-verse/air@v1.61.7

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

CMD ["air"]
